### ISSUE TITLE
junit-testing-common:implement missing tests and fix code smells

### ISSUE THREAD

**Issue by silkentrance** [coldrye-java/junit-testing#19]
## TODO

- [ ] clean up code
- [ ] implement missing tests
- [ ] fix code smells

**Comment by silkentrance** [comment]
Will be dealt with in a general refactoring story.
