### ISSUE TITLE
file-assertions: Implement missing tests and fix existing code smells

### ISSUE THREAD

**Issue by silkentrance** [coldrye-java/junit-testing#23]
## TODO

- [ ] clean up code
- [ ] implement missing tests
- [ ] fix code smells

**Comment by silkentrance** [comment]
Will be dealt with in a general refactoring story.
