### ISSUE TITLE
junit-env-extension: release 1.4.0

### ISSUE THREAD

**Issue by silkentrance** [coldrye-java/junit-testing#34]
## Release

A new release is going to be prepared for the specified component.

## TODO

- [x] update change log
- [x] update documentation (maven coordinates)
- [x] update dependencies
- [x] integrate into dev (rebase/merge existing other branches)
- [x] merge into master
- [x] create release tag (<component>/<version>)
