### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by silkentrance** [coldrye-java/junit-testing#36]
For ongoing work we need to prepare issue templates

## TODO

- [x] Standard new issue template
- [x] Bug template
- [x] Feature template
- [x] Release template
- [x] Refactoring template
- [x] Wiki page from where one can create new issues using different templates
see https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/
- [x] Wiki page from where one can create developer / maintainer issues from

### Standard New Issue Template

- Use case: User clicks on ``New Issue``
- Template: .github/ISSUETEMPLATE.md
- Labels: unspecified
- Milestone: triage-unspecified

```
Thank you for getting into touch with us.

You are about to file an unspecified issue.

Please use one of the provided issue templates instead.

In order to do this, you have to navigate to

https://github.com/coldrye-java/junit-testing/wiki/Report+Issue

and create your issue from there.

Alternatively you can remove this placeholder text and file an unspecified issue.
```

### Question Template

- Usecase: User has a general or component specific question
- Template: .github/question.md
- Labels: general|component,question
- Milestone: triage-new-questions
- Title: [(general|component-name):]

```
## Question
Enter your question here
```

### Bug Report Template

- Usecase: User wants to file a general or component specific bug report
- Template: .github/bug.md
- Labels: general|component,bug,PR appreciated
- Milestone: triage-new-bugs
- Title: [(general|component-name):]

```
## Bug Report

### Summary
Enter a short summary of the issue you are experiencing here.

### System Configuration

- Version of the Software
- Maven Version
- Java JDK/JRE Version
- Operating System and OS Version

### Actual Behaviour
Please describe the actual behaviour of the system here.

### Expected Behaviour
Please describe what your expectations would have been.

### Stack Trace
You may provide us with a stack trace if available.

### How to Reproduce
How may we be able to reproduce this bug? A Gist or a link to a failing build or even your project would be fine.

### References
Add additional references here.
```

### Feature Request Template (.github/feature.md)

- Usecase: User wants to file a general or component specific feature request
- Template: .github/feature.md
- Labels: general|component,feature,PR appreciated
- Milestone: triage-new-features
- Title: [(general|component-name):]

```
## Feature Request

### Summary
Enter a short summary of the feature you want us to realise.

### System Configuration

- Version of the Software
- Maven Version
- Java JDK/JRE Version
- Operating System and OS Version

### Description
Please describe the new feature in detail here.

### References
Add additional references here.
```

### Release Template

- Usecase: Maintainer wants to file a general or component specific release request
- Template: .github/release.md
- Project: Release Management
- Labels: general|component,release-planned
- Workflow Labels: release-planned|release-staged|release-cancelled|release-published

```
A new release for the specified component.

## TODO

- [ ] update change log
- [ ] update documentation (maven coordinates)
- [ ] update dependencies
```

### Increase Coverage Template

- Labels: technical debt, coverage
- Milestone: triage-coverage

### Fix Code Smells Template

- Labels: technical debt, quality
- Milestone: triage-quality

### Revise API Documentation Template

- Use case: Developer wants to make a general or component specific revision of the api docs
- Labels: general|component,technical debt,documentation
- Milestone: triage-documentation

### Refactoring Template

- Use case: Developer wants to make a general or component specific refactoring
- Template: .github/refactoring.md
- Labels: component,technical debt,maintainability,reusability,testability,compatibility
- Milestone: triage-refactoring

```
## Refactoring

### Summary
Please enter a short summary of what you are going to do.

### Affected Components
Please list here the components that will be affected by the refactoring.

## Classification

- [ ] breaking change
- [ ] increases or maintains existing compatibility
- [ ] increases or maintains existing testability
- [ ] increases or maintains existing reusability
- [ ] increases or maintains existing maintainability

## Description
If you feel like it, add an in-depth description of the planned refactoring here.

## References
Add additional references here.
```

**Comment by silkentrance** [comment]
Works just fine. Will need to add additional links in the readme though.
